disabled_rules:
  - line_length
opt_in_rules:
  - empty_count
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_top_level_acl
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - superfluous_disable_command
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_optional_binding
included:
  - Cauli

force_cast: warning
force_try: warning

file_length:
  warning: 500
  error: 1200

reporter: "xcode"