language: objective-c
osx_image: xcode11.3

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

install:
  - bundle install
  - cd $TRAVIS_BUILD_DIR

script:
  # These exports are a workaround for a cocoapod issue: https://github.com/CocoaPods/CocoaPods/issues/7708
  - export EXPANDED_CODE_SIGN_IDENTITY=""
  - export EXPANDED_CODE_SIGN_IDENTITY_NAME=""
  - export EXPANDED_PROVISIONING_PROFILE=""
  - bundle exec rake test

before_script:
  - export LANG=en_US.UTF-8
  - bundle exec danger