name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: macos-12
    strategy:
      matrix:
        include: # selection of https://github.com/actions/runner-images/blob/macOS-12/20230916.1/images/macos/macos-12-Readme.md#installed-simulators
          - xcode: "13.4.1"
            ios: "15.5"
            device: "iPhone 8"
          - xcode: "14.2"
            ios: "16.2"
            device: "iPhone 8"
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    name: "test ios ${{matrix.ios}}"
    steps:
    - uses: actions/checkout@v3
    - name: "Select Xcode ${{matrix.xcode}}"
      run: sudo xcode-select -switch /Applications/Xcode_${{matrix.xcode}}.app && /usr/bin/xcodebuild -version
    - name: Run Unit Tests on ${{matrix.ios}} ${{matrix.device}}
      run: xcodebuild -workspace Cauliframework.xcworkspace -scheme 'Cauliframework' -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,name=${{matrix.device}},OS=${{matrix.ios}}' -configuration Debug clean test
  build-example-app:
    runs-on: macos-12
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    name: "Build Example App"
    steps:
    - uses: actions/checkout@v3
    - name: Build Example App
      run: xcodebuild -workspace Example/cauli-ios-example/cauli-ios-example.xcworkspace -scheme 'Cauliframework'  -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2' -configuration Release clean build
  build-spm:
    runs-on: macos-12
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    name: "Build SPM"
    steps:
    - uses: actions/checkout@v3
    - name: Build SPM
      run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios16.2-simulator"
